[package]
name = "recursive_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
risc0-zkvm = "1.2.0"
serde = "1.0.216"
# For Accelerated sha2
# sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
